name:                functive-hs
version:             0.1.0.0
github:              "githubuser/functive-hs"
license:             BSD3
author:              "Henry Blanchette"
maintainer:          "blancheh@reed.edu"
copyright:           "2019 Henry Blanchette"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A simple modular extendible statically-typed symbolic programming language with dependent types.
# category:            Programming languages

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/functive-hs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.10.2
- re2 >= 0.3
- transformers >= 0.5

library:
  source-dirs: src

executables:
  functive-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functive-hs

tests:
  functive-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - functive-hs
